### PR TITLE
Conform to isort

### PR DESCRIPTION
**Pull request by tristan957**
Signed-off-by: Tristan Partin <tpartin@micron.com>

### CODE REVIEW

**Comment by alexttx** [comment]
What's the benefit in conforming to isort?

**Comment by tristan957** [comment]
Consistent format of import statements and order

**Comment by alexttx** [comment]
> Consistent format of import statements and order

This adds development overhead for insignificant benefit.  CI will cause failures that would be a mystery to most developers.

**Comment by tristan957** [comment]
The CI provides a diff of what needs to change. How is this any different from the include order discussions we have been having for HSE?

**Comment by alexttx** [comment]
In C, inconsistent include order can cause subtle bugs.  Is that true with Python too?  I assume Python namespaces project against that.

**Comment by tristan957** [comment]
You are right in that they don't, but I still feel like code uniformity is a nice thing to strive for that way no one has to think where does this thing go or how should I format this piece of code.

I would argue even in C, a well-defined include order is nice for the same reasons ^.

**Pull request merged**
